version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    ports:
      - "8080:80"
    environment:
      DB_HOST: ${DB_HOST}
      DB_DBNAME: ${DB_DBNAME}
      DB_USER: ${DB_USER}
      DB_PASSWD: ${DB_PASSWD}
    networks:
      - bibliodrive-network
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: db.Dockerfile
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - bibliodrive-network

  caddy:
    image: caddy:2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    networks:
      - bibliodrive-network
    depends_on:
      - app

networks:
  bibliodrive-network:
